file1=open('sample.txt','w')
f=str(input("Enter text to write to the file:"))
file1.writelines(f+'\n')
print("Data successfully written to file.")
file1.close()
file2=open('sample.txt','a')
w=str(input("Enter text to append to the file:"))
file2.writelines(w)
print("Data successfully written to file.")
print("Data successfully appended.")
file2.close()
file3=open('sample.txt','r+')
print("Final content of output.txt")
r=file3.read()
print(r)
file3.close()
